version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.0
jobs:
  build-image:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.12"
          docker_layer_caching: true
      - run: make build-linux
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t thejokersthief/cartographer-dsl:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u thejokersthief --password-stdin
          docker push thejokersthief/cartographer-dsl:$TAG
  generate-config:
    docker:
      - image: thejokersthief/cartographer-dsl:$CIRCLE_SHA1
        auth:
          username: thejokersthief
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Generate Pipeline generated_config.yml file
          command: cartographer-dsl --file .circleci/_config.jsonnet > generated_config.yml
      - continuation/continue:
          parameters: '{}'
          configuration_path: generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - build-image
      - generate-config:
          requires: ['build-image']
          filters:
            branches:
              only:
                - /.*/
            tags:
              only:
                - /.*/
